openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
tags:
  name: Users
  description: For the users
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: A list of users
